Linear Regression is not suitable for classification because it predicts continuous values, while classification requires discrete classes (e.g., 0 or 1).

Example

Suppose we want to classify whether a student passes:

Hours Studied	Pass
1	0
2	0
3	0
4	1
5	1


A linear regression model might learn:

y=0.3x−0.8

Now for:

x = 2 → y = -0.2
x = 4 → y = 0.4
x = 7 → y = 1.3

Problems
1. Predictions can be less than 0 or greater than 1

For classification, probabilities should be between 0 and 1.

Linear regression can predict:

-0.5
1.7
2.3

These are not valid probabilities.

2. Sensitive to outliers

A few extreme points can significantly change the regression line and affect classification decisions.

3. Decision boundary is not probabilistic

Classification often needs:

"What is the probability that this belongs to class 1?"

Linear regression doesn't naturally provide valid probabilities.

Why Logistic Regression Works

Instead of a straight line, logistic regression applies a sigmoid function:

p=
1+e
−z
1
	​


This converts any number into a value between 0 and 1.

Example:

z = -10 → p ≈ 0
z = 0 → p = 0.5
z = 10 → p ≈ 1

Then:

p ≥ 0.5 → Class 1
p < 0.5 → Class 0
Visual Intuition

Linear Regression

Class 0    Class 1

0----0----1----1

---------/---------
        line

Predictions can go below 0 or above 1.

Logistic Regression

Probability

1.0 |        ______
    |      /
0.5 |----/
    |  /
0.0 |/
    +----------------

The S-shaped curve keeps probabilities between 0 and 1.

Interview Answer

Linear Regression is not used for classification because it predicts continuous values and can produce outputs outside the valid probability range [0,1]. Logistic Regression uses a sigmoid function to convert predictions into probabilities between 0 and 1, making it suitable for classification tasks.

Performance Metrics:

1. confusion matrix
2. Accuracy
3. Precision
4. Recall
5. F_Beta score

A Confusion Matrix is used to evaluate how well a Logistic Regression classifier performs.

For a binary classification problem, it looks like this:

| Actual \ Predicted | Positive (1)        | Negative (0)        |
| ------------------ | ------------------- | ------------------- |
| Positive (1)       | True Positive (TP)  | False Negative (FN) |
| Negative (0)       | False Positive (FP) | True Negative (TN)  |


Example

Suppose we have the following confusion matrix:

| Actual \ Predicted | 1  | 0  |
| ------------------ | -- | -- |
| 1                  | 50 | 10 |
| 0                  | 5  | 35 |
Metrics from Confusion Matrix
Accuracy
Accuracy=TP+TN+FP+FN//TP+TN
	​

Accuracy=
50+35+5+10//50+35=100//85=85%
Precision
Precision=
TP+FP//TP
	​

Precision=
50+5//50=0.909

Recall (Sensitivity)
Recall=
TP+FN//TP
	​

Recall=
50+10//50=0.833

F1 Score
F1=Precision+Recall//2×Precision×Recall
	​

F1=0.87

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import make_classification

In [4]:
# Creating dataset

X,y=make_classification( n_samples=1000,n_features=10,n_classes=2,random_state=42)

X.shape,y.shape

((1000, 10), (1000,))

In [5]:
X=pd.DataFrame(X)
y=pd.DataFrame(y)

In [6]:
X.head()

,0,1,2,3,4,5,6,7,8,9
0,0.964799,-0.066449,0.986768,-0.358079,0.997266,1.181890,-1.615679,-1.210161,-0.628077,1.227274
1,-0.916511,-0.566395,-1.008614,0.831617,-1.176962,1.820544,1.752375,-0.984534,0.363896,0.209470
2,-0.109484,-0.432774,-0.457649,0.793818,-0.268646,-1.836360,1.239086,-0.246383,-1.058145,-0.297376
3,1.750412,2.023606,1.688159,0.006800,-1.607661,0.184741,-2.619427,-0.357445,-1.473127,-0.190039
4,-0.224726,-0.711303,-0.220778,0.117124,1.536061,0.597538,0.348645,-0.939156,0.175915,0.236224

In [7]:
y.head()

   0
0  0
1  1
2  1
3  0
4  1

In [8]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

In [9]:
X_train.shape

(700, 10)

In [10]:
from sklearn.linear_model import LogisticRegression

logistic=LogisticRegression()

In [11]:
logistic.fit(X_train,y_train)

/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [15]:
y_pred=logistic.predict(X_test)

y_pred

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0])

In [16]:
# Performance metircs

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [17]:
score=accuracy_score(y_test,y_pred)

score

0.8466666666666667

In [18]:
cm=confusion_matrix(y_test,y_pred)

cm

array([[118,  17],
       [ 29, 136]])

In [21]:
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.80      0.87      0.84       135
           1       0.89      0.82      0.86       165

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300

In [32]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression

params = {
    'penalty': ['l1', 'l2','elasticnet'],
    'C': [100, 10, 1, 0.1, 0.01],
    'solver': ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']
}

cv = StratifiedKFold()

logistic = LogisticRegression()

model = GridSearchCV(
    estimator=logistic,
    param_grid=params,
    scoring='accuracy',
    cv=cv,
    n_jobs=-1
)

model.fit(X_train, y_train)

print("Best Parameters:", model.best_params_)
print("Best Accuracy:", model.best_score_)

/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Best Parameters: {'C': 0.01, 'penalty': 'l2', 'solver': 'lbfgs'}
Best Accuracy: 0.8785714285714287

 of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(

In [28]:
model

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(),
             param_grid={'C': [100, 10, 1, 0.1, 0.01],
                         'penality': ['l1', 'l2', 'elasticnet', None],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [35]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report


y_pred=model.predict(X_test)

accuracy=accuracy_score(y_test,y_pred)

cm=confusion_matrix(y_test,y_pred)

report=classification_report(y_test,y_pred)

print(accuracy)
print(cm)
print(report)

0.8533333333333334
[[124  11]
 [ 33 132]]
              precision    recall  f1-score   support

           0       0.79      0.92      0.85       135
           1       0.92      0.80      0.86       165

    accuracy                           0.85       300
   macro avg       0.86      0.86      0.85       300
weighted avg       0.86      0.85      0.85       300

In [36]:
# RandomizedCV

# It will select random parameters

In [41]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

X, y = make_classification(
    n_samples=1000,
    n_features=10,
    n_informative=3,
    n_classes=3,
    random_state=42
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3
)

In [42]:
X_train.shape

(700, 10)

In [43]:
X_train

array([[-0.04817869, -0.5239488 ,  0.57244531, ...,  1.97234448,
         0.94964306,  0.46425124],
       [ 1.15419767,  0.70156291, -0.93100171, ...,  0.31444459,
         2.66009185, -0.35895839],
       [-0.32575606, -0.07354436,  0.25062823, ..., -0.62742073,
        -0.66449672,  1.22885655],
       ...,
       [-0.36703399, -0.50884119, -0.00407284, ...,  0.64189412,
        -1.04867144, -1.02969624],
       [-0.26990399,  0.72628752, -0.56155775, ..., -1.78115841,
         0.11360534, -2.23046802],
       [-0.09621943, -1.15270821,  0.21000831, ..., -1.67176127,
        -0.4187543 ,  2.71033164]], shape=(700, 10))

In [44]:
y_train

array([2, 1, 2, 0, 0, 1, 2, 1, 1, 0, 0, 1, 1, 0, 2, 2, 2, 1, 2, 2, 1, 1,
       0, 0, 2, 1, 2, 1, 2, 0, 0, 2, 0, 0, 1, 0, 0, 2, 2, 2, 2, 2, 1, 1,
       1, 0, 1, 0, 2, 2, 0, 0, 2, 0, 1, 0, 2, 2, 1, 2, 1, 2, 2, 1, 0, 1,
       0, 1, 1, 2, 1, 0, 1, 2, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 1, 1, 2, 2,
       1, 0, 1, 2, 2, 0, 1, 1, 2, 0, 2, 0, 0, 0, 0, 2, 2, 0, 1, 2, 1, 0,
       2, 0, 0, 0, 0, 0, 1, 2, 2, 1, 2, 1, 2, 0, 1, 2, 2, 0, 0, 2, 0, 1,
       1, 1, 0, 0, 2, 0, 2, 2, 1, 2, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 2, 2,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 2, 0, 2, 2, 0, 1, 0, 0, 0, 0, 2, 1,
       0, 2, 1, 2, 1, 0, 2, 1, 0, 0, 1, 0, 1, 1, 1, 2, 1, 2, 2, 0, 2, 1,
       1, 1, 0, 2, 0, 0, 0, 2, 0, 0, 1, 2, 0, 2, 2, 0, 1, 2, 0, 2, 0, 1,
       1, 0, 1, 2, 1, 2, 2, 2, 2, 1, 2, 1, 1, 1, 0, 1, 1, 2, 0, 0, 0, 0,
       2, 1, 1, 1, 1, 0, 1, 0, 2, 0, 0, 0, 0, 0, 2, 1, 0, 1, 0, 1, 2, 0,
       1, 2, 2, 0, 1, 2, 0, 2, 2, 1, 1, 0, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2,
       0, 2, 2, 1, 2, 1, 0, 2, 1, 1, 1, 1, 1, 2, 1, 0, 1, 0, 1, 2, 1, 2,
       2, 1, 2, 2, 1, 2, 1, 2, 1, 1, 0, 0, 0, 2, 1, 1, 2, 2, 2, 0, 2, 2,
       0, 1, 2, 0, 2, 2, 2, 0, 0, 0, 1, 1, 0, 2, 1, 1, 1, 0, 2, 1, 0, 2,
       2, 1, 2, 0, 2, 1, 1, 1, 2, 2, 1, 0, 0, 1, 1, 1, 0, 0, 2, 2, 2, 0,
       1, 0, 1, 0, 2, 0, 1, 2, 0, 2, 0, 0, 1, 1, 0, 1, 1, 2, 1, 1, 2, 2,
       0, 2, 1, 2, 2, 2, 1, 1, 1, 2, 0, 0, 1, 1, 1, 0, 2, 1, 0, 0, 2, 2,
       2, 0, 2, 1, 0, 0, 1, 1, 1, 2, 0, 2, 2, 0, 2, 1, 0, 1, 0, 2, 1, 0,
       2, 1, 2, 0, 2, 2, 0, 0, 2, 1, 0, 0, 1, 0, 2, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 2, 1, 0, 1, 1, 1, 1, 1, 0, 2, 0, 1, 1, 1, 1, 2, 0, 1, 2,
       0, 0, 0, 2, 2, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 2, 0, 1, 1, 0, 2, 1,
       2, 1, 0, 2, 1, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 0, 2, 0, 2, 1, 2, 0,
       1, 1, 1, 0, 2, 1, 1, 0, 1, 0, 1, 0, 0, 1, 2, 0, 0, 2, 0, 1, 0, 0,
       0, 2, 1, 1, 2, 0, 2, 1, 0, 1, 1, 2, 0, 0, 0, 0, 0, 2, 2, 1, 2, 1,
       0, 2, 1, 1, 0, 1, 2, 2, 0, 2, 2, 1, 2, 0, 0, 1, 2, 2, 2, 2, 0, 0,
       0, 2, 0, 2, 0, 2, 2, 1, 1, 0, 0, 0, 2, 2, 1, 2, 1, 0, 2, 0, 1, 2,
       0, 1, 2, 2, 0, 2, 2, 2, 0, 2, 1, 2, 0, 2, 1, 2, 1, 0, 1, 1, 0, 2,
       2, 1, 2, 2, 0, 2, 1, 2, 2, 2, 1, 2, 1, 1, 0, 2, 0, 0, 1, 0, 1, 2,
       2, 0, 0, 0, 1, 0, 0, 0, 1, 2, 2, 0, 0, 0, 2, 1, 0, 0, 0, 1, 1, 2,
       2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 2, 0, 2, 0, 2, 1, 2])

In [47]:
from sklearn.linear_model import LogisticRegression

model=LogisticRegression()

In [48]:
model.fit(X_train,y_train)

LogisticRegression()

In [49]:
y_pred=model.predict(X_test)

In [50]:
y_pred

array([2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 0, 2, 0, 2, 2, 2, 2, 0, 1, 1, 2, 1,
       0, 0, 0, 1, 2, 0, 2, 2, 0, 0, 0, 2, 0, 1, 2, 2, 2, 2, 2, 0, 2, 1,
       2, 1, 1, 0, 0, 0, 2, 2, 1, 2, 0, 0, 2, 2, 1, 1, 1, 0, 2, 0, 0, 2,
       0, 2, 1, 1, 2, 1, 2, 1, 1, 2, 0, 2, 0, 0, 1, 2, 1, 0, 1, 2, 2, 0,
       2, 2, 1, 0, 2, 2, 2, 2, 2, 0, 1, 0, 1, 2, 0, 2, 1, 0, 0, 1, 1, 2,
       1, 0, 1, 2, 2, 1, 1, 2, 0, 1, 2, 2, 1, 0, 0, 0, 2, 0, 1, 0, 1, 0,
       1, 2, 2, 1, 0, 0, 2, 2, 1, 1, 2, 0, 1, 0, 2, 2, 0, 0, 1, 0, 1, 0,
       1, 2, 2, 0, 1, 1, 2, 2, 1, 1, 1, 1, 2, 0, 1, 0, 1, 2, 2, 0, 2, 1,
       2, 2, 1, 1, 0, 2, 0, 2, 0, 2, 2, 0, 2, 0, 0, 1, 0, 2, 2, 0, 0, 2,
       1, 1, 0, 0, 0, 1, 2, 1, 0, 2, 2, 2, 2, 1, 1, 0, 2, 2, 2, 2, 2, 1,
       2, 1, 0, 1, 0, 2, 2, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 2, 2, 1,
       1, 2, 2, 0, 1, 0, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 2, 0, 2, 0, 0, 1, 2, 0, 2, 1, 0, 2, 2, 1, 1, 0, 0,
       1, 0, 2, 1, 0, 2, 0, 0, 0, 0, 2, 0, 2, 2])

In [52]:
from sklearn.metrics import accuracy_score

accuracy=accuracy_score(y_test,y_pred)


print(accuracy)

0.6766666666666666